# Generated by Django 4.2.6 on 2023-11-07 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_alter_order_cod_alter_orderlog_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='warranty',
            field=models.DateField(blank=True, null=True),
        ),
    ]
