# Generated by Django 4.2.6 on 2023-10-29 02:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_product_sn_starting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='sn',
            field=models.CharField(max_length=16, validators=[django.core.validators.RegexValidator(code='invalid_hexadecimal', message='Enter a valid hexadecimal number.', regex='^[0-9a-fA-F]*$')]),
        ),
    ]
