# Generated by Django 4.2.6 on 2023-10-29 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_stock_sn'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='verify_count',
            field=models.IntegerField(default=0),
        ),
    ]
