# Generated by Django 4.2.6 on 2023-11-07 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_remove_warranty_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='warrantylog',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
