# Generated by Django 4.2.6 on 2024-02-09 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_warrantylog_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='category/'),
        ),
        migrations.AlterField(
            model_name='warranty',
            name='status',
            field=models.CharField(choices=[('Received', 'Received'), ('Pending', 'Pending'), ('Processing', 'Processing'), ('Ready for Delivery', 'Ready for Delivery')], default='Select', max_length=100),
        ),
        migrations.AlterField(
            model_name='warrantylog',
            name='status',
            field=models.CharField(choices=[('Received', 'Received'), ('Pending', 'Pending'), ('Processing', 'Processing'), ('Ready for Delivery', 'Ready for Delivery'), ('Delivered', 'Delivered')], default='Pending', max_length=100),
        ),
    ]
