# Generated by Django 4.2.6 on 2024-02-09 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_category_image_alter_warranty_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subcategory',
            old_name='image',
            new_name='icon',
        ),
    ]
